/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "square.h"

int *
square_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Funcao square(%d) foi chamada\n", *argp);
	result = (*argp)*(*argp);

	return &result;
}
