/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQUARE_H_RPCGEN
#define _SQUARE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SQUARE_PROG 0x00001111
#define SQUARE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define square 1
extern  int * square_1(int *, CLIENT *);
extern  int * square_1_svc(int *, struct svc_req *);
extern int square_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define square 1
extern  int * square_1();
extern  int * square_1_svc();
extern int square_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQUARE_H_RPCGEN */
