/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMA_H_RPCGEN
#define _SOMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Numeros {
	int a;
	int b;
};
typedef struct Numeros Numeros;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(Numeros *, CLIENT *);
extern  int * add_1_svc(Numeros *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Numeros (XDR *, Numeros*);

#else /* K&R C */
extern bool_t xdr_Numeros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMA_H_RPCGEN */
